categories = {
    "Fruits": [
        "Custard Apple - 500 gm (Pack of 2)",
        "Pineapple - 1 Kg",
        "Himalayan Country Apple (12000 Ft.+) - 2pcs (FnV)",
        "Banana (Robusta) - 500 gm",
        "Guava - 250 gm (Pack of 2)",
        "Pomegranate Kesar - 500 gm",
        "Kiwi Green - 2 Pcs Pack (Pack of 2)",
        "Orange Imported - 500 gm",
        "Papaya (Ripe) - 1 Kg",
        "Plum - 500 gm",
        "Sapota (Chiku) - 500 gm",
        "Apple (Shimla) - 500 gm",
        "Apple (Royal Gala) - 500 gm (Pack of 2)",
        "Muskmelon - 1 Kg",
        "Avocado Haas - 1 Pc",
        "Ber Apple - 500 gm",
        "Grapes Bangalore Blue - 250 gm (Pack of 2)",
        "Indian Pears (Naspati) - 500gm",
        "Apple Fuji - 500 gm",
        "Guava Thai - 500 gm",
        "Mini Orange - 250 gm",
        "Pears Nakh - 500gm",
        "Banana Yellaki - 500 gm",
        "Banana Amruthapani - 500 gm",
        "Banana Karpooravalli - 1 Kg",
        "Apple Royal Gala Economy - 500 gm",
        "Pears Beauty - 500 gm",
        "Grapefruit  1pc (Imported) - 350 gm",
        "Longan - 250 gm",
        "Baby Apple - 500 gm",
        "Apple Red Delicious (Imported)  - 500 gm",
        "Blueberry - 50 gm",
        "Blueberry - 50 gm (Pack of 2)",
        "Passion Fruit - 250 gm",
        "Apple Green - 500 gm",
        "Mango Lassi"  # beverage but fruit-based
    ],
    "Vegetables": [
        "Tomato Desi - 500 gm",
        "Okra (Bhindi) - 250 gm",
        "Pumpkin Green - 500 gm",
        "Onion Premium - 500 gm",
        "Potato - 500 gm",
        "Cabbage(Patta Gobhi) - 500 gm",
        "Cucumber Hybrid (Kheera) - 500 gm",
        "Beetroot(Chukundar) - 500 gm",
        "Carrot (Local) - 500 gm",
        "Carrot (Ooty) - 250 gm",
        "Green Chilli (Hari Mirch) - 100 gm",
        "Lemon (Nimboo) - 150 gm",
        "Coriander (Dhaniya) - 100 gm",
        "Mint(Pudina) - 100 gm (without roots)",
        "Bottle Gourd (Lauki) Approx. 650gm to 800gm",
        "Ginger(Adrak) -100 gm",
        "Brinjal Purple Long - 500 gm",
        "Capsicum (Shimla Mirch) - 500 gm",
        "Cauliflower (Phool Gobhi) - 500 gm",
        "Spinach Premium(Paalak) - 250 gm",
        "Fenugreek (Methi) - 250 gm",
        "Ridge Gourd/Desi Tori - 500 gm",
        "Brinjal (Round) - 500 gm",
        "Drumsticks - 250 gm",
        "Knol Khol (Gaanth Gobhi) - 500 gm",
        "Sponge Gourd(Turai) - 500 gm",
        "Pointed Gourd(Parwal) - 250 gm",
        "Ash Gourd (Petha) - 500 gm",
        "Colocasia(Arbi) - 500 gm",
        "Spring Onion - 250 gm",
        "Amaranthus Green - 250 gm",
        "Amaranthus Red - 250 gm",
        "Forest Bitter Gourd - 500 gm",
        "Curry Leaf(Kadi Patta) - 100 gm",
        "Garlic (Lahsun) - 100 gm",
        "Coriander (Dhania) - 50 gm",
        "Radish(Mooli) - 500 gm",
        "Zucchini - 300 gm",
        "Raw Mango - 500 gm",
        "Sweet Corn 2 pcs - 1 Packet",
        "Sweet Potato(Shakarkand) - 500 gm",
        "Cowpea (Lobia) - 500 gm",
        "French Beans - 250 gm"
    ],
    "Staples": [
        "Cold Pressed Mustard Oil - 1400ml (700ml x 2)",
        "Cold Pressed Groundnut Oil - 700ml",
        "Cold Pressed Coconut Oil - 700ml",
        "Cold Pressed Coconut Oil - 1400ml (700ml x 2)",
        "Non-refined Mustard Oil - 1.8 Ltr",
        "Non-refined Groundnut Oil - 1.8 Ltr",
        "Non-refined Sunflower Oil - 3.6 Ltr (1.8Ltr x 2)",
        "Basmati Rice (Daily Choice) - 800 gm",
        "Indrayani Rice - 4 kg",
        "Ambemohar Rice - 800gm",
        "Gobindo Bhog Rice - 800 gm",
        "100% Desi Whole Wheat Atta - 4kg",
        "100% Lokwan (MP) Atta - 4kg",
        "Maida - 900gm (450gm x 2)",
        "Besan - 900gm (450gm x 2)",
        "Poha Thick - 900gm (450gm x 2)",
        "Suji (Rawa) - 900gm (450gm x 2)",
        "Jaggery Powder - 900gm (450gm x 2)",
        "Moong Dal Mogar - 200gm",
        "Toor Dal - 450 gm",
        "Urad Dal - 900gm (450gm x 2)",
        "Chana Dal - 900gm (450gm x 2)",
        "Rajma Chitra - 900gm (450gm x 2)",
        "Kabuli Chana - 450 gm",
        "Brown (Kala) Chana - 450 gm",
        "Ragi Millets - 450gm",
        "Jowar Millet - 450gm",
        "Bajra Millet- 450gm",
        "Raw Peanuts - 900gm (450gm x 2)",
        "Iodized Sea Salt - 900gm",
        "Sulphurless Sugar - 900gm",
        "Natural Rock Salt - 900gm",
        "Farm Honey - 900gm (450gm x 2)",
        "NMR Farm Honey - 475 gm",
        "Strong Hing - 45gm",
        "Turmeric Powder - 90gm",
        "Coriander Powder - 90gm",
        "Mustard Yellow - 90gm",
        "Cumin (Jeera) Whole - 180gm"
    ],
    "Snacks": [
        "Ajwain Mathri - 390gm (130gm x 3)",
        "Butter Kaju Pista Cookies - 300gm (100gm x 3)",
        "Butter Atta Biscuit",
        "Potato Chips - Cream & Onion - 40gm",
        "Potato Chips - Himalayan Pink Salt - 40gm",
        "Potato Chips - Homestyle Masala - 40gm",
        "Potato Chips - Homestyle Masala - 80gm (40gm x 2)",
        "Phool Makhana - 150gm",
        "Phool Makhana - 300gm (150gm x 2)",
        "Mix Farsan - 120 gm",
        "Moong Papad - 200gm (100gm x 2)",
        "Dry Bhel - 100 gm",
        "Multigrain Maida Free Khakra - 200gm (100gm x 2)",
        "Methi Khakra - 200gm",
        "Roasted Peanuts - Himalayan Pink & Black Salt - 280gm (70gm x 4)",
        "Chocolate Peanut Butter",
        "Disney Chocolate Pancake Mix - 120gm",
        "Anardana Candy - 55gm"
    ],
    "Dairy": [
        "Cow Milk - 500 ML",
        "Buffalo Milk - 500 ML",
        "Cow Milk - 450 ML",
        "A2 Cow Milk -  1 L",
        "Low Fat Cow Milk - 500 ML",
        "High Protein Paneer-180 gm",
        "Ghar Jaisa Dahi - 400 GM (Curd)",
        "Buffalo Milk Curd - 400gm",
        "Low Fat Dahi - 400 GM (Curd)",
        "Taaza Paneer - 180gm",
        "High Protein Paneer (Pack of 2)",
        "Taaza Paneer(Buffalo Milk)  - 180 GM",
        "Cow Milk butter Unsalted",
        "Desi Danedar Ghee - 850 ML",
        "Buffalo Ghee",
        "Desi Danedar Ghee Combo - 850ml x 2",
        "Full Cream Shrikhand (Badam & Pista) - 200gm",
        "Strawberry Yogurt- 85gm",
        "Blueberry Yogurt (Pack of 2)",
        "High Protein Greek Yoghurt Blueberry",
        "High Protein Greek Yoghurt Vanilla",
        "Disney Mango Badam Drinking Yogurt- 160gm",
        "Disney Strawberry Badam Drinking yogurt (Probiotic)",
        "Disney Vanilla Badam Drinking Yogurt"
    ],
    "Coconut Water": [
        "Country Coconut Water - 1 pc",
        "Coconut Water Cup - 1 pc (160ml)",
        "Coconut Water Cup - 2 pc (320ml)",
        "Country Coconut Water - Combo"
    ]
}
